(load "src/shared/util.rkt")

(define (run-util-tests)
   (display "tst/shared/util.rkt") (newline)
   (init-samples sample-wavfile)
   (test-write-wavfile-bytes-for-channel)
   (test-set-wavfile-samples-for-channel)
   (test-write-wavfile-bytes)
   (test-set-wavfile-samples)
)

;; 1 second of stereo audio, all samples are 0
(define sample-wavfile (wavfile 'little 1 2 44100 88200 4 16 44 176400 (make-vector 2)))

(define (test-write-wavfile-bytes-for-channel)
   (letrec ((bytes (make-bytes (+ (wavfile-chunkstart sample-wavfile) (wavfile-chunksize sample-wavfile)) 1)) 
            (control (bytes-append (make-bytes 44 1) 
                                   (make-bytes (wavfile-chunksize sample-wavfile) 0))))
        (write-wavfile-bytes-for-channel bytes sample-wavfile 0)
        (check-false (bytes=? bytes control))
        (write-wavfile-bytes-for-channel bytes sample-wavfile 1)
        (check-true (bytes=? bytes control))))

(define (test-write-wavfile-bytes)
   (letrec ((bytes (make-bytes (+ (wavfile-chunkstart sample-wavfile) (wavfile-chunksize sample-wavfile)) 1)) 
            (control (bytes-append (make-bytes 44 1) 
                                   (make-bytes (wavfile-chunksize sample-wavfile) 0))))
        (write-wavfile-bytes bytes sample-wavfile)
        (check-true (bytes=? bytes control))))

(define (test-set-wavfile-samples-for-channel)
   (letrec ((bytes (make-bytes (+ (wavfile-chunkstart sample-wavfile) (wavfile-chunksize sample-wavfile)) 1))
         (left (make-vector 44100 257))
         (right (make-vector 44100 257)))
        (set-wavfile-samples-for-channel bytes sample-wavfile 0)
        (check-equal? left (vector-ref (wavfile-samples sample-wavfile) 0))
        (check-not-equal? right (vector-ref (wavfile-samples sample-wavfile) 1))
        (set-wavfile-samples-for-channel bytes sample-wavfile 1)
        (check-equal? left (vector-ref (wavfile-samples sample-wavfile) 0))
        (check-equal? right (vector-ref (wavfile-samples sample-wavfile) 1)))
   (vector-fill! (vector-ref (wavfile-samples sample-wavfile) 0) 0)
   (vector-fill! (vector-ref (wavfile-samples sample-wavfile) 1) 0))

(define (test-set-wavfile-samples)
   (letrec ((bytes (make-bytes (+ (wavfile-chunkstart sample-wavfile) (wavfile-chunksize sample-wavfile)) 1))
         (left (make-vector 44100 257))
         (right (make-vector 44100 257)))
        (set-wavfile-samples bytes sample-wavfile)
        (check-equal? left (vector-ref (wavfile-samples sample-wavfile) 0))
        (check-equal? right (vector-ref (wavfile-samples sample-wavfile) 1)))
   (vector-fill! (vector-ref (wavfile-samples sample-wavfile) 0) 0)
   (vector-fill! (vector-ref (wavfile-samples sample-wavfile) 1) 0))
