#!/bin/bash

## credit to Frank Szczerba http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
##

/proj/racket/bin/racket -f $DIR/tst/load-all-tests.rkt -e '(run-all-tests)(newline)'
