(load "src/fileio.rkt")

(define (run-fileio-tests)
   (display "tst/fileio.rkt") (newline)
   (test-is-mp3?)
   (test-is-wav?)
   (test-write-wavfile-bytes-for-channel)
   (test-set-wavfile-samples-for-channel)
   (test-write-wavfile-to-bytes)
   (test-set-wavfile-samples)
   (test-file-writer-reader))

;; 1 second of stereo audio, all samples are 0
(define sample-wavfile (wavfile 'little 1 2 44100 176400 4 2 44 176400 (vector (make-vector 44100) (make-vector 44100))))

(define (test-file-writer-reader)
    (vector-set! (vector-ref (wavfile-samples sample-wavfile) 0) 0 -44)
    (wavfile->file sample-wavfile "/tmp/_test")
    (let [(w (file->wavfile "/tmp/_test"))]
         (check-equal? (wavfile-endianess sample-wavfile) (wavfile-endianess w))
         (check-equal? (wavfile-audioformat sample-wavfile) (wavfile-audioformat w))
         (check-equal? (wavfile-channels sample-wavfile) (wavfile-channels w))
         (check-equal? (wavfile-samplerate sample-wavfile) (wavfile-samplerate w))
         (check-equal? (wavfile-byterate sample-wavfile) (wavfile-byterate w))
         (check-equal? (wavfile-blockalign sample-wavfile) (wavfile-blockalign w))
         (check-equal? (wavfile-bytespersample sample-wavfile) (wavfile-bytespersample w))
         (check-equal? (wavfile-chunkstart sample-wavfile) (wavfile-chunkstart w))
         (check-equal? (wavfile-chunksize sample-wavfile) (wavfile-chunksize w))
         (check-equal? (wavfile-samples sample-wavfile) (wavfile-samples w)))
    (vector-set! (vector-ref (wavfile-samples sample-wavfile) 0) 0 0))

(define (test-is-mp3?)
   (check-false (is-mp3? "testwav.wav"))
   (check-true (is-mp3? "testmp3.mp3")))

(define (test-is-wav?)
   (check-true (is-wav? "testwav.wav"))
   (check-false (is-wav? "testmp3.mp3")))

(define (test-write-wavfile-bytes-for-channel)
   (letrec ((bytes (make-bytes (+ (wavfile-chunkstart sample-wavfile) (wavfile-chunksize sample-wavfile)) 1))
            (control (bytes-append (make-bytes 44 1)
                                   (make-bytes (wavfile-chunksize sample-wavfile) 0))))
        (write-wavfile-bytes-for-channel bytes sample-wavfile 0)
        (check-false (bytes=? bytes control))
        (write-wavfile-bytes-for-channel bytes sample-wavfile 1)
        (check-true (bytes=? bytes control))))

(define (test-write-wavfile-to-bytes)
   (letrec ((bytes (make-bytes (+ (wavfile-chunkstart sample-wavfile) (wavfile-chunksize sample-wavfile)) 1))
            (control (bytes-append (make-bytes 44 1)
                                   (make-bytes (wavfile-chunksize sample-wavfile) 0))))
        (write-wavfile-to-bytes sample-wavfile bytes)
        (check-true (bytes=? bytes control))))

(define (test-set-wavfile-samples-for-channel)
   (letrec ((bytes (make-bytes (+ (wavfile-chunkstart sample-wavfile) (wavfile-chunksize sample-wavfile)) 1))
         (left (make-vector 44100 257))
         (right (make-vector 44100 257)))
        (set-wavfile-samples-for-channel bytes sample-wavfile 0)
        (check-equal? left (vector-ref (wavfile-samples sample-wavfile) 0))
        (check-not-equal? right (vector-ref (wavfile-samples sample-wavfile) 1))
        (set-wavfile-samples-for-channel bytes sample-wavfile 1)
        (check-equal? left (vector-ref (wavfile-samples sample-wavfile) 0))
        (check-equal? right (vector-ref (wavfile-samples sample-wavfile) 1)))
   (vector-fill! (vector-ref (wavfile-samples sample-wavfile) 0) 0)
   (vector-fill! (vector-ref (wavfile-samples sample-wavfile) 1) 0))

(define (test-set-wavfile-samples)
   (letrec ((bytes (make-bytes (+ (wavfile-chunkstart sample-wavfile) (wavfile-chunksize sample-wavfile)) 1))
         (left (make-vector 44100 257))
         (right (make-vector 44100 257)))
        (set-wavfile-samples bytes sample-wavfile)
        (check-equal? left (vector-ref (wavfile-samples sample-wavfile) 0))
        (check-equal? right (vector-ref (wavfile-samples sample-wavfile) 1)))
   (vector-fill! (vector-ref (wavfile-samples sample-wavfile) 0) 0)
   (vector-fill! (vector-ref (wavfile-samples sample-wavfile) 1) 0))
