(require rackunit)

(load-relative "../src/requirements.rkt")
(load-relative "../src/constants.rkt")
(load-relative "../src/fileio.rkt")
(load-relative "../src/frequencycontroller.rkt")
(load-relative "../src/wavfile.rkt")
(load-relative "../src/encoder.rkt")
(load-relative "../src/decoder.rkt")

(load-relative "fileio.rkt")
(load-relative "wavfile.rkt")
(load-relative "frequencycontroller.rkt")
(load-relative "encoder.rkt")
(load-relative "decoder.rkt")
(load-relative "encoder-decoder.rkt")

(define (run-all-tests)
   (run-fileio-tests)
   (run-wavfile-tests)
   (run-frequencycontroller-tests)
   (run-encoder-tests)
   (run-decoder-tests)
   (run-encoder-decoder-tests)
   (void))
