(load "src/decoder/lsb.sch")

(define (run-lsb-decoding-tests)
   (display "tst/decoder/lsb.sch") (newline)
   (get-lsb-test)
   (get-lsb-from-bytevector-test)
   (get-payload-from-carrier-lsb-test))

(define (get-lsb-test)
  (assert (= (get-lsb 7) 1))
  (assert (= (get-lsb 8) 0)))

(define (get-lsb-from-bytevector-test)
  (let ((bv (make-bytevector 2 0)))
     (bytevector-s8-set! bv 1 1)
     (assert (= (get-lsb-from-bytevector bv 0) 0))
     (assert (= (get-lsb-from-bytevector bv 1) 1))))

(define (get-payload-from-carrier-lsb-test)
  (let ((payload (make-bytevector 2 0)) (carrier (make-bytevector 32 0)))
    (bytevector-set! payload 0 4)
    (bytevector-set! payload 1 3)
    (bytevector-set! carrier 10 1)
    (bytevector-set! carrier 28 7)
    (bytevector-set! carrier 30 13)
    (assert (bytevector=? payload (get-payload-from-carrier-lsb carrier 0))))

  (let ((payload (make-bytevector 2 0)) (carrier (make-bytevector 32 0)))
    (bytevector-set! payload 0 4)
    (bytevector-set! payload 1 3)
    (bytevector-set! carrier 11 1)
    (bytevector-set! carrier 29 7)
    (bytevector-set! carrier 31 13)
    (assert (bytevector=? payload (get-payload-from-carrier-lsb carrier 1)))))
